services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=jhin'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27016:27017'
    volumes:
      - 'mongo-dev:/data/db'

volumes:
  mongo-dev:
    external: true
