spring:
  application:
    name: jhin
  data:
    mongodb:
      database: jhin
      host: localhost
      port: 27016
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: basic

logging:
  level:
    org.willwin.jhin: TRACE
data:
  crawl:
    update-all-accounts: false
    update-all-matches: false
    update-all-match-features: false
    crawl-new-accounts: false
