spring:
  application:
    name: jhin
  threads:
    virtual:
      enabled: true
  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true

riot:
  match-list-start: 2021-06-16
